### Looping through Paths (Solutions)

This assignment is due on:
- Tuesday 17th at 11:59 pm for Applied Research 2 Students
- Wednesday 18th at 11:59 pm for Economic Research Seminar Students

Send me your Jupyter Notebook to my email (eddiezago500@gmail.com) in the following format: hw1_name_surname.ipynb. Make sure to copy the whole 'assignment1' folder to your DropBox or local computer and use relative paths, as we have seen in class. I should be able to run all your codes without changing the paths.

e.g: '../data/input/file.xlsx'


#### Overall Instructions:
For the first assignment we will be aggregating reports that were sent daily to AfricaCheck with the most viral posts from Facebook and Twitter. These reports are divided into several files, which you can check out in the data folder. We are going to append each one of these reports, to obtain a final data set with all the posts sent over the time period.

We have three different types of reports: Facebook data, Viral Content in Twitter data and Facebook Top Posts.

In [1]:
import pandas as pd
import numpy as np
import os

#### 1) Setting up the list of dates:

1.1) Import the file 'dates_experiment.xlsx' located in 'data/input/' folder. Use the function .head() to take a look at it:

In [13]:
df_dates = pd.read_excel('../data/input/dates_experiment.xlsx')
df_dates.head()

        date
0 2022-06-20
1 2022-06-21
2 2022-06-22
3 2022-06-23
4 2022-06-24

1.2) Notice that the dates in this file go from 20/06/2022 to 14/12/2022 including weekends. The reports were only sent from 2022-10-16 to 2022-10-27 only from Sunday to Thursday. 

- Filter the data frame to obtain one with the dates that the report was sent.
- Create a list with the dates of the report.

Hint: Use the weekday() function to filter the Data Frame by day of the week.

In [14]:
df_dates = df_dates[(df_dates['date'] > '2022-10-15') & (df_dates['date'] < '2022-10-28')]
df_dates

          date
118 2022-10-16
119 2022-10-17
120 2022-10-18
121 2022-10-19
122 2022-10-20
123 2022-10-21
124 2022-10-22
125 2022-10-23
126 2022-10-24
127 2022-10-25
128 2022-10-26
129 2022-10-27

In [16]:
# Filtering Weekends using weekday(): 
# Google: 'How to obtain the weekday from a date pandas' and you have three options
# https://stackoverflow.com/questions/28009370/get-weekday-day-of-week-for-datetime-column-of-dataframe

df_dates['weekday'] = df_dates['date'].apply(lambda x: x.weekday())
df_dates = df_dates[(df_dates['weekday'] != 4) & (df_dates['weekday'] != 5)].reset_index(drop=True)
df_dates.drop(['weekday'], axis=1, inplace=True)
df_dates

        date
0 2022-10-16
1 2022-10-17
2 2022-10-18
3 2022-10-19
4 2022-10-20
5 2022-10-23
6 2022-10-24
7 2022-10-25
8 2022-10-26
9 2022-10-27

In [17]:
# Export list as string of dates:
list_dates = list(df_dates['date'].astype(str))
list_dates

['2022-10-16',
 '2022-10-17',
 '2022-10-18',
 '2022-10-19',
 '2022-10-20',
 '2022-10-23',
 '2022-10-24',
 '2022-10-25',
 '2022-10-26',
 '2022-10-27']

1.3) EXTRA POINT: Build a function that:

- Takes as input a data frame, the name of the column with the dates, a start and a final date.
- Filters the data frame by those two dates.
- Returns a list with the filtered dates.

In [12]:
def get_time_list(df, var_date = 'date', initial = '2022-10-15', end = '2022-10-28'):
    df = df[(df[var_date] > initial) & (df[var_date] < end)]
    list_dates = list(df[var_date].astype(str))
    
    return list_dates

In [18]:
# Using the function:
df_dates_prueba = pd.read_excel('../data/input/dates_experiment.xlsx')
list_prueba = get_time_list(df_dates_prueba, initial = '2022-10-18', end = '2022-10-28')
list_prueba

['2022-10-19',
 '2022-10-20',
 '2022-10-21',
 '2022-10-22',
 '2022-10-23',
 '2022-10-24',
 '2022-10-25',
 '2022-10-26',
 '2022-10-27']

#### 2) Aggregating Facebook

2.1) Notice that in each folder there is a file named 'facebook.xlsx'. Loop through these folders using the list you just created, import the 'facebook.xlsx' files and append them one in top of the other to generate an aggregated data set with all the posts from this report sent over this period of time:

In [21]:
# Using append you get all this warnings since that function is going to be removed in the future, but it works
df_final = pd.DataFrame()
for date in list_dates:
    df = pd.read_excel(f'../data/{date}/facebook.xlsx')
    df_final = df_final.append(df)
    
df_final = df_final.reset_index(drop=True)
df_final.info()

C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3254 entries, 0 to 3253
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   facebook_handle     3125 non-null   object
 1   text                3182 non-null   object
 2   date                3254 non-null   object
 3   date_consulted      3254 non-null   datetime64[ns]
 4   angryCount          3254 non-null   int64
 5   careCount           3254 non-null   int64
 6   hahaCount           3254 non-null   int64
 7   likeCount           3254 non-null   int64
 8   loveCount           3254 non-null   int64
 9   sadCount            3254 non-null   int64
 10  thankfulCount       3254 non-null   int64
 11  wowCount            3254 non-null   int64
 12  n_organizations     238 non-null    float64
 13  n_persons           238 non-null    float64
 14  n_locations         238 non-null    float64
 15  n_money             238 non-null    float64
 16  n_dates             238 non-null    float64
 17  n_socialgroups      238 non-null    float64
 18  n_laws              238 non-null    float64
 19  n_quantities        238 non-null    float64
 20  n_ordinalnumbers    238 non-null    float64
 21  n_cardinalnumbers   238 non-null    float64
 22  n_percentages       238 non-null    float64
 23  n_events            238 non-null    float64
 24  shareCount          3254 non-null   int64
 25  commentCount        3254 non-null   int64
 26  url                 3254 non-null   object
 27  total_interactions  3254 non-null   int64
 28  treatment           3035 non-null   float64
dtypes: datetime64[ns](1), float64(13), int64(11), object(4)
memory usage: 737.4+ KB

C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)
C:\Users\Dell\AppData\Local\Temp\ipykernel_11344\3123624202.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_final.append(df)

2.2) Create a folder named '../data/facebook_out/' using the os package as seen in the notes (do not forget to define the function) and export the aggregated data set there as parquet.

In [22]:
def create_folder(directory):
    """Create folder"""
    # Create target Directory if don't exist
    if not os.path.exists(directory):
        os.mkdir(directory)
        print("Directory ", directory, " created ")
    else:
        print("Directory ", directory, " already exists")
        
create_folder('../data/facebook_out/')

df_final.to_parquet('../data/facebook_out/agg_facebook.parquet.gzip')

Directory  ../data/facebook_out/  created

#### 3) Viral Content from Twitter

3.1) Notice that in each folder there are two files named 'viral_content_twitter_verifiable.xlsx' and 'viral_content_twitter_not_verifiable.xlsx'. 

- Loop through these folders using the dates list and the type list provided alrady to you.
- Import the files and add a column named 'verfiability' which will be a dummy that is 1 if the report is 'verifiable' and 0 if 'not_verifiable'.
- Append them one in top of the other to generate an aggregated data set with all the posts from this report sent over this period of time:

Hint: Do a nested loop across both lists, only two fors

In [25]:
# No tenían que saber esto pero para que se vea mejor el output

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [30]:
type_list = ['verifiable', 'not_verifiable']

In [31]:
# Using pd.concat([]) (no necesitaban, a mi me acaba de salir el warning)
df_stage = pd.DataFrame()
for status in type_list:
    df_status = pd.DataFrame()
    for fecha in list_dates:
        df = pd.read_excel(f'../data/{fecha}/viral_content_twitter_{status}.xlsx')
        if status == 'verifiable':
            df['verifiability'] = 1
        else: 
            df['verifiability'] = 0
        df_status = pd.concat([df_status, df])
    df_stage = pd.concat([df_stage, df_status])
    
df_stage = df_stage.reset_index(drop=True)
df_stage

,twitter_handle,text,possibly_sensitive,date,date_consulted,like_count,quote_count,reply_count,retweet_count,n_organizations,...,n_laws,n_quantities,n_ordinalnumbers,n_cardinalnumbers,n_percentages,n_events,url,total_interactions,text_clean,verifiability
0,MrOdanz,RT @wikileaks: Julian Assange speaking in 2011...,False,2022-10-16T19:40:26.000Z,2022-10-16,0,0,0,53862,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,https://twitter.com/MrOdanz/status/15817318147...,53862,rt julian assange speaking in the goal is to u...,1
1,MrOdanz,"RT @Snowden: After this clip, Assange was forc...",False,2022-10-16T19:39:51.000Z,2022-10-16,0,0,0,11944,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,https://twitter.com/MrOdanz/status/15817316702...,11944,rt after this clip assange was forced into asy...,1
2,MrOdanz,RT @JackPosobiec: BREAKING: Xi Jinping opens C...,False,2022-10-16T06:16:30.000Z,2022-10-16,0,0,0,5744,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,https://twitter.com/MrOdanz/status/15815295005...,5744,rt breaking xi jinping opens ccp summit by ann...,1
3,MrOdanz,"RT @PeterObi: Recently, several social media r...",False,2022-10-16T19:50:22.000Z,2022-10-16,0,0,0,5574,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,https://twitter.com/MrOdanz/status/15817343134...,5574,rt recently several social media reports have ...,1
4,MrOdanz,RT @KyivIndependent: ⚡️ Israeli minister: Time...,False,2022-10-16T18:56:11.000Z,2022-10-16,0,0,0,4970,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,https://twitter.com/MrOdanz/status/15817206787...,4970,rt israeli minister time has come for israel t...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,miraaikie,RT @david_r_morgan: Agenda 2030 is not a consp...,False,2022-10-27T06:25:59.000Z,2022-10-27,0,0,0,599,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://twitter.com/miraaikie/status/158551815...,599,rt agenda is not conspiracy theory it unfoldin...,0
814,KakwenzaRukira,Atagegya https://t.co/bGtBZhGoNE,False,2022-10-27T10:51:55.000Z,2022-10-27,517,1,30,44,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://twitter.com/KakwenzaRukira/status/1585...,592,atagegya,0
815,Gentlements,RT @EmbassyofRussia: 🇷🇺FM Sergey #Lavrov: We w...,False,2022-10-27T10:50:14.000Z,2022-10-27,0,0,0,564,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://twitter.com/Gentlements/status/1585584...,564,rt fm sergey we want united amp independent vo...,0
816,kabelodick,RT @fredtheinvestor: You must be on crack to t...,False,2022-10-27T04:21:18.000Z,2022-10-27,0,0,0,544,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://twitter.com/kabelodick/status/15854867...,544,rt you must be on crack to think that r p sala...,0
817,miraaikie,"RT @BohemianAtmosp1: Daily reminder, the vacci...",False,2022-10-27T15:02:05.000Z,2022-10-27,0,0,0,511,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://twitter.com/miraaikie/status/158564803...,511,rt daily reminder the vaccines are not safe ma...,0

3.2) Create a folder named '../data/twitter_out/' using the os package as seen in the notes and export the aggregated data set there as parquet.

In [32]:
create_folder('../data/twitter_out/')

df_final.to_parquet('../data/twitter_out/agg_twitter.parquet.gzip')

Directory  ../data/twitter_out/  created

#### 3) Facebook Top Posts

3.1) Notice that in each folder there are 6 files named 'facebook_top_posts_{country}_verifiable.xlsx' and 'facebook_top_posts_{country}_not_verifiable.xlsx', where country are KE (Kenya), ZA (South Africa) and NG (Nigeria)

- Loop through these folders using the dates list, the type list and the country list provided already to you.
- Import the files and add a column named 'verfiability' which will be a dummy that is 1 if the report is 'verifiable' and 0 if 'not_verifiable', and a column with the country from which this report is from.
- Append them one in top of the other to generate an aggregated data set with all the posts from this report sent over this period of time:

Hint: Do a nested loop across *the three* lists, with 3 nested fors

In [24]:
type_list = ['verifiable', 'not_verifiable']
country_list = ['KE', 'ZA', 'NG']

In [28]:
df_stage = pd.DataFrame()
for status in type_list:
    df_status = pd.DataFrame()
    for country in country_list:
        df_country = pd.DataFrame()
        for fecha in list_dates:
            df = pd.read_excel(f'../data/{fecha}/facebook_top_posts_{country}_{status}.xlsx')
            df['country'] = country
            if status == 'verifiable':
                df['verifiability'] = 1
            else: 
                df['verifiability'] = 0
            df_country = df_country.append(df)
        df_status = df_status.append(df_country)
    df_stage = df_stage.append(df_status)
    
df_stage = df_stage.reset_index(drop=True)
df_stage

,facebook_handle,text,Platform Id,date,date_consulted,likeCount,loveCount,wowCount,hahaCount,sadCount,...,n_events,shareCount,commentCount,url,total_interactions,id_pair,rand,treatment,country,verifiability
0,EricTenHagOfficial,Sir Alex Ferguson presents Cristiano Ronaldo w...,100083215483166,2022-10-16 13:09:01,2022-10-17,49110,8868,31,55,6,...,0.0,649,305,https://www.facebook.com/100083215483166/posts...,59446,1,6864,0,KE,1
1,williamsamoei,"Interdenominational church service, Green Stad...",100044138484360,2022-10-16 07:04:09,2022-10-17,9607,318,17,12,4,...,0.0,453,1902,https://www.facebook.com/100044138484360/posts...,12340,1,35085,1,KE,1
2,williamsamoei,"Give praise to the LORD, proclaim His name; ma...",100044138484360,2022-10-16 11:23:10,2022-10-17,9714,155,0,8,0,...,0.0,186,667,https://www.facebook.com/100044138484360/posts...,10743,2,11428,0,KE,1
3,williamsamoei,"Interdenominational church service, Green Stad...",100044138484360,2022-10-16 10:02:55,2022-10-17,7962,263,8,11,6,...,0.0,165,1010,https://www.facebook.com/100044138484360/posts...,9438,2,53378,1,KE,1
4,arochofred,Leeds 0-0 Arsenal Leeds United's Premier Leagu...,100044468978229,2022-10-16 13:36:46,2022-10-17,5961,8,5,43,4,...,0.0,6,309,https://www.facebook.com/100044468978229/posts...,6340,3,14117,0,KE,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,jerryuchechukwu.ezeii,JESUS IS REAL ! What God Cannot Do Does Not Ex...,100044401690362,2022-10-27 07:58:47,2022-10-27,4880,1256,1,1,0,...,NaN,472,1965,https://www.facebook.com/100044401690362/posts...,8613,48,82355,1,NG,0
5996,TransformersNG,YOU ARE UNSTOPPABLE!! Prophetic Prayer Hour [ ...,100064391361367,2022-10-27 04:49:49,2022-10-27,378,201,2,5,2,...,NaN,1681,6213,https://www.facebook.com/100064391361367/posts...,8490,49,1682,0,NG,0
5997,Lovedoctorjoshuadaniels,"Lack of s*x can cause depression, headache, an...",103636481038654,2022-10-27 11:09:16,2022-10-27,4861,33,54,911,8,...,NaN,93,2608,https://www.facebook.com/103636481038654/posts...,8575,49,47647,1,NG,0
5998,NaN,Beautiful picture of the day ❤❤❤ #photography ...,100078006421870,2022-10-27 10:56:18,2022-10-27,7181,990,2,1,2,...,NaN,67,144,https://www.facebook.com/100078006421870/posts...,8445,50,30033,0,NG,0
5999,NaN,For over 25 years of my career i often hide my...,100044550484314,2022-10-27 06:31:36,2022-10-27,7065,660,8,13,0,...,NaN,33,655,https://www.facebook.com/100044550484314/posts...,8474,50,46127,1,NG,0

In [29]:
create_folder('../data/facebook_top_out/')

df_final.to_parquet('../data/facebook_top_out/agg_facebook_top.parquet.gzip')

Directory  ../data/facebook_top_out/  created